#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_placement second_child

yabai -m config external_bar all:32:0

yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse on

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^DeepL$' manage=off
yabai -m rule --add app='^Things$' manage=off
yabai -m rule --add app='^Azure VPN Client$' manage=off


yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='Settings$' manage=off

